import 'package:kami_face_oracle/core/deity.dart';

const List<Deity> deities = <Deity>[
  Deity(
      id: 'amatera',
      nameJa: 'Amatera',
      nameEn: 'Solar Goddess',
      role: '太陽の女神',
      colorHex: '#F6B34B',
      symbolAsset: 'assets/illustrations/amatera.png',
      expr: 1,
      skin: 1,
      shape: 1,
      claim: 1,
      shortMessage: '希望と行動力が高まる日。'),
  Deity(
      id: 'delphos',
      nameJa: 'Delphos',
      nameEn: 'God of Oracles',
      role: '神託の神',
      colorHex: '#375B9E',
      symbolAsset: 'assets/illustrations/delphos.png',
      expr: 0,
      skin: 1,
      shape: 1,
      claim: 1,
      shortMessage: '冷静な判断が冴える。'),
  Deity(
      id: 'skura',
      nameJa: 'Skura',
      nameEn: 'Goddess of Blossoms',
      role: '春の女神',
      colorHex: '#E8A7B8',
      symbolAsset: 'assets/illustrations/skura.png',
      expr: 1,
      skin: 1,
      shape: 0,
      claim: 0,
      shortMessage: 'やさしさが運を運ぶ。'),
  Deity(
      id: 'mimika',
      nameJa: 'Mimika',
      nameEn: 'Goddess of Wisdom',
      role: '知恵の女神',
      colorHex: '#1D6E73',
      symbolAsset: 'assets/illustrations/mimika.png',
      expr: 0,
      skin: 1,
      shape: 0,
      claim: 1,
      shortMessage: '知恵と直感のバランス。'),
  Deity(
      id: 'tenkora',
      nameJa: 'Tenkora',
      nameEn: 'Fox Deity',
      role: '狐の神',
      colorHex: '#D8622E',
      symbolAsset: 'assets/illustrations/tenkora.png',
      expr: 1,
      skin: 1,
      shape: 0,
      claim: 1,
      shortMessage: '変化に飛び乗ろう。'),
  Deity(
      id: 'yatael',
      nameJa: 'Yatael',
      nameEn: 'God of Guidance',
      role: '導きの神',
      colorHex: '#5FAF6C',
      symbolAsset: 'assets/illustrations/yatael.png',
      expr: 1,
      skin: 1,
      shape: 1,
      claim: 0,
      shortMessage: '協調と信頼が鍵。'),
  Deity(
      id: 'noirune',
      nameJa: 'Noirune',
      nameEn: 'Moon Deity',
      role: '月の神',
      colorHex: '#2E3850',
      symbolAsset: 'assets/illustrations/noirune.png',
      expr: 0,
      skin: 1,
      shape: 0,
      claim: 0,
      shortMessage: '静かな集中が実る。'),
  Deity(
      id: 'shiran',
      nameJa: 'Shiran',
      nameEn: 'White Fox Deity',
      role: '白狐の神',
      colorHex: '#CFC7B0',
      symbolAsset: 'assets/illustrations/shiran.png',
      expr: 1,
      skin: 0,
      shape: 0,
      claim: 0,
      shortMessage: '自由な発想で前進。'),
  Deity(
      id: 'fatemis',
      nameJa: 'Fatemis',
      nameEn: 'God of Fate',
      role: '運命の神',
      colorHex: '#6B4B2A',
      symbolAsset: 'assets/illustrations/fatemis.png',
      expr: 1,
      skin: 0,
      shape: 1,
      claim: 1,
      shortMessage: '決断力が試される。'),
  Deity(
      id: 'amanoira',
      nameJa: 'Amanoira',
      nameEn: 'God of Destiny',
      role: '宿命の神',
      colorHex: '#4A3A6A',
      symbolAsset: 'assets/illustrations/amanoira.png',
      expr: 0,
      skin: 0,
      shape: 1,
      claim: 1,
      shortMessage: '洞察が本質を射抜く。'),
  Deity(
      id: 'verdatsu',
      nameJa: 'Verdatsu',
      nameEn: 'God of Time',
      role: '時の神',
      colorHex: '#2B5B5E',
      symbolAsset: 'assets/illustrations/verdatsu.png',
      expr: 1,
      skin: 0,
      shape: 1,
      claim: 0,
      shortMessage: 'いま、この瞬間に集中。'),
  Deity(
      id: 'kanonis',
      nameJa: 'Kanonis',
      nameEn: 'Goddess of Compassion',
      role: '慈愛の女神',
      colorHex: '#6DC49A',
      symbolAsset: 'assets/illustrations/kanonis.png',
      expr: 0,
      skin: 0,
      shape: 0,
      claim: 0,
      shortMessage: '包容力が流れを整える。'),
  Deity(
      id: 'ragias',
      nameJa: 'Ragias',
      nameEn: 'Heavenly Deity',
      role: '雷神',
      colorHex: '#D26A24',
      symbolAsset: 'assets/illustrations/ragias.png',
      expr: 1,
      skin: 0,
      shape: 1,
      claim: 1,
      shortMessage: '情熱で壁を破る。'),
  Deity(
      id: 'sylna',
      nameJa: 'Sylna',
      nameEn: 'Goddess of Healing',
      role: '森の女神',
      colorHex: '#5E8C4A',
      symbolAsset: 'assets/illustrations/sylna.png',
      expr: 0,
      skin: 0,
      shape: 0,
      claim: 0,
      shortMessage: '自然と調和し整う。'),
  Deity(
      id: 'osiria',
      nameJa: 'Osiria',
      nameEn: 'Sea Goddess',
      role: '海の女神',
      colorHex: '#3B91B5',
      symbolAsset: 'assets/illustrations/osiria.png',
      expr: 1,
      skin: 1,
      shape: 0,
      claim: 1,
      shortMessage: '美と愛が巡る。'),
  Deity(
      id: 'tenmira',
      nameJa: 'Tenmira',
      nameEn: 'Trickster Deity',
      role: '未来の神',
      colorHex: '#B96E2B',
      symbolAsset: 'assets/illustrations/tenmira.png',
      expr: 0,
      skin: 1,
      shape: 0,
      claim: 0,
      shortMessage: 'ひらめきが未来を開く。'),
  Deity(
      id: 'yorusi',
      nameJa: 'Yorusi',
      nameEn: 'Sun Deity',
      role: '太陽の神',
      colorHex: '#EAA54A',
      symbolAsset: 'assets/illustrations/yorusi.png',
      expr: 1,
      skin: 1,
      shape: 1,
      claim: 1,
      shortMessage: '勇気と活力が満ちる。'),
  Deity(
      id: 'shisaru',
      nameJa: 'Shisaru',
      nameEn: 'Starlight Goddess',
      role: '星の女神',
      colorHex: '#24365A',
      symbolAsset: 'assets/illustrations/shisaru.png',
      expr: 0,
      skin: 1,
      shape: 0,
      claim: 0,
      shortMessage: '夜空の静けさが支えに。'),
];
